apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: goapp-github-secref
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/yangcao/goapp-github-secref:85f6673a2153ac1f8994c95139a601683dce0b20@sha256:3354cf92be6997495e88231cbfcb0e66dc3f97ba2a45bae628b1a40c3fe24c9a
        name: container-image  
